FROM ubuntu:20.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y bind9
COPY named.conf.local /etc/bind/named.conf.local
COPY db.empresa.local /etc/bind/db.empresa.local
COPY db.192.168.1 /etc/bind/db.192.168.1
EXPOSE 53
CMD ["named", "-f"]

