FROM ubuntu:20.04
RUN apt-get update && apt-get install -y nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY sites-available/www.conf /etc/nginx/sites-available/www.conf
COPY sites-available/intranet.conf /etc/nginx/sites-available/intranet.conf
RUN ln -s /etc/nginx/sites-available/www.conf /etc/nginx/sites-enabled/ && \
    ln -s /etc/nginx/sites-available/intranet.conf /etc/nginx/sites-enabled/
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]

