FROM ubuntu:20.04

# Instala o isc-dhcp-server
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y isc-dhcp-server && \
    mkdir -p /var/lib/dhcp && \
    touch /var/lib/dhcp/dhcpd.leases && \
    chmod 666 /var/lib/dhcp/dhcpd.leases && \
    rm -rf /var/lib/apt/lists/*

# Copia o arquivo de configuração
COPY dhcpd.conf /etc/dhcp/dhcpd.conf

# Força o DHCP a escutar na eth0
RUN sed -i 's/INTERFACESv4=""/INTERFACESv4="eth0"/' /etc/default/isc-dhcp-server

EXPOSE 67/udp

CMD ["dhcpd", "-4", "-f", "-d"]

